# zOS/core/L4_Orchestration/s_zRaven/zRaven_modules/utils/clear_manager.py
"""zClear — remove committed dev-flow scratch files + orphaned zRaven output.

The cleanup counterpart to zCommit (commit_manager.py). Where zCommit is purely
additive, zClear is purely subtractive — but only ever removes what's either
(a) safely backed up by a real zCommit, or (b) unreferenced junk nothing points
to anymore:

  dev flows   `_zSpark.<flow>.zolo` + its `zRaven/zRaven.<flow>.zolo` are
              removed ONLY when a commit exists for that flow AND the commit's
              flow-owned snapshot is byte-identical to the current working
              copy (--force skips the byte-identical check, never the "a
              commit must exist at all" check — clearing something with zero
              backup anywhere is never allowed)
  canonical   a real `zSpark.<name>.zolo` (no underscore) is NEVER touched —
              multiple canonical sparks in one app are a deliberate developer
              choice (bonus/alt entry points), not zClear's business, full stop
  shots       `zRaven/zShots/<X>/` is NEVER source — it's disposable proof
              output regenerated by the next --run (and separately archived by
              zCommit if one was ever made) — so it is WIPED unconditionally
              for every flow on every --clear, canonical or dev, committed or
              not; ownership protection above only ever covers spark/raven
  orphans     a `zRaven/zShots/<X>/` matching no zSpark OR _zSpark file at all
              is wiped the same way — nothing references it, always safe

Every clear (and every skip, with its reason) is appended to
zVersions/clears.csv — the project-wide audit trail, mirroring commits.csv.
"""

from __future__ import annotations

import csv
import filecmp
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

_LEDGER_COLUMNS = ("id", "timestamp", "flow", "action", "reason")


def _flow_name(spark_path: Path) -> str:
    return spark_path.stem.split(".", 1)[-1]


def _latest_commit_dir(workspace: Path, flow: str) -> Optional[Path]:
    flow_dir = workspace / "zVersions" / "commits" / flow
    if not flow_dir.exists():
        return None
    nums = [int(p.name[1:]) for p in flow_dir.iterdir() if p.is_dir() and p.name[1:].isdigit()]
    return (flow_dir / f"c{max(nums)}") if nums else None


def _matches_last_commit(workspace: Path, commit_dir: Path, spark_path: Path, raven_path: Path) -> bool:
    """True if the flow-owned working files are byte-identical to the commit's snapshot."""
    snapshot = commit_dir / "snapshot"
    for src in (spark_path, raven_path):
        if not src.exists():
            return False
        rel = src.relative_to(workspace)
        archived = snapshot / rel
        if not archived.exists() or not filecmp.cmp(src, archived, shallow=False):
            return False
    return True


def _append_ledger(workspace: Path, flow: str, action: str, reason: str) -> None:
    ledger = workspace / "zVersions" / "clears.csv"
    ledger.parent.mkdir(parents=True, exist_ok=True)
    write_header = not ledger.exists()
    with ledger.open("a", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(_LEDGER_COLUMNS), extrasaction="ignore")
        if write_header:
            writer.writeheader()
        row_id = 1
        if not write_header:
            with ledger.open("r", encoding="utf-8") as rfh:
                row_id = sum(1 for _ in rfh)
        writer.writerow({
            "id": row_id,
            "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "flow": flow,
            "action": action,
            "reason": reason,
        })


def clear_workspace(workspace: Path, flow_filter: Optional[str] = None,
                     force: bool = False, dry_run: bool = False) -> dict:
    """Clear committed dev flows + orphaned shot folders from workspace.

    Returns {"cleared": [...], "skipped": [(flow, reason), ...]}.
    """
    cleared: list[str] = []
    skipped: list[tuple[str, str]] = []
    shots_wiped: list[str] = []

    dev_sparks = sorted(workspace.glob("_zSpark.*.zolo"))
    if flow_filter:
        dev_sparks = [p for p in dev_sparks if _flow_name(p) == flow_filter]

    live_flow_names: set[str] = set()
    for p in workspace.glob("zSpark.*.zolo"):
        live_flow_names.add(_flow_name(p))
    for p in workspace.glob("_zSpark.*.zolo"):
        live_flow_names.add(_flow_name(p))

    for spark_path in dev_sparks:
        flow = _flow_name(spark_path)
        raven_path = workspace / "zRaven" / f"zRaven.{flow}.zolo"
        shots_path = workspace / "zRaven" / "zShots" / flow

        commit_dir = _latest_commit_dir(workspace, flow)
        if commit_dir is None:
            reason = "no commit exists — run `z raven --commit` first"
            skipped.append((flow, reason))
            if not dry_run:
                _append_ledger(workspace, flow, "skipped", reason)
            continue

        matches = _matches_last_commit(workspace, commit_dir, spark_path, raven_path)
        if not matches and not force:
            reason = (f"working copy drifted from {commit_dir.name} — "
                       f"commit again or pass --force")
            skipped.append((flow, reason))
            if not dry_run:
                _append_ledger(workspace, flow, "skipped", reason)
            continue

        reason = f"backed up in {commit_dir.relative_to(workspace)}" + ("" if matches else " (forced, drifted)")
        if not dry_run:
            spark_path.unlink(missing_ok=True)
            if raven_path.exists():
                raven_path.unlink()
            if shots_path.exists():
                shutil.rmtree(shots_path)
            _append_ledger(workspace, flow, "cleared", reason)
        cleared.append(flow)
        live_flow_names.discard(flow)  # its shots are already gone above, nothing left to wipe/sweep

    # ── zShots/ — shots are NEVER source, only proof output regenerated by the
    # next --run (and separately archived by zCommit if one was ever made), so
    # every flow's shots get wiped here regardless of canonical/dev status —
    # ownership protection (above) only ever applies to spark/raven files ──────
    shots_root = workspace / "zRaven" / "zShots"
    if shots_root.exists():
        for shot_dir in sorted(shots_root.iterdir()):
            if not shot_dir.is_dir() or not any(shot_dir.iterdir()):
                continue
            name = shot_dir.name
            if flow_filter and name != flow_filter:
                continue
            if name in live_flow_names:
                if not dry_run:
                    shutil.rmtree(shot_dir)
                    _append_ledger(workspace, name, "shots_wiped", "zShots reset — regenerates on next --run")
                shots_wiped.append(name)
            elif not flow_filter:
                # orphaned — nothing (no zSpark or _zSpark) references this name at all
                if not dry_run:
                    shutil.rmtree(shot_dir)
                    _append_ledger(workspace, name, "cleared", "orphaned zShots — no matching spark")
                cleared.append(f"{name} (orphaned shots)")

    return {"cleared": cleared, "skipped": skipped, "shots_wiped": shots_wiped}
