"""
Pygments Lexer for .zolo files

AUTO-GENERATED by generate_pygments_lexer.py
DO NOT EDIT MANUALLY - Changes will be overwritten!

Generated: 2026-01-19 19:39:11
Source: zlsp token patterns
Maintainer: Run generate_pygments_lexer.py to regenerate
"""

from pygments.lexer import RegexLexer, bygroups, include
from pygments.token import (
    Comment, Keyword, Name, String, Number, Punctuation,
    Operator, Whitespace, Generic, Error
)

__all__ = ['ZoloLexer']


class ZoloLexer(RegexLexer):
    r"""
    Lexer for .zolo declarative configuration files.
    
    Supports:
    - Root keys (Page_Header:, Core_Concepts_Section:)
    - Display events (zH1:, zText:, zMD:)
    - Metadata keys (_zClass:, _zStyle:, _zId:)
    - Special keys (zMeta:, zRBAC:, ~zNavBar*)
    - Properties (label:, content:, color:)
    - Modifiers (*, !, ^, ~)
    - Type hints ((int), (str), (bool))
    - Escape sequences (\\uXXXX, \\UXXXXXXXX)
    - Comments (# lines)
    - Values (strings, numbers, booleans, arrays)
    
    Token Mapping (zlsp → Pygments):
    - rootKey → Name.Class (bold, prominent)
    - uiElementKey (z*) → Name.Function (blue/cyan)
    - nestedKey → Name.Attribute (properties)
    - escapeSequence → String.Escape (bright)
    - comment → Comment.Single (dim)
    - typeHint → Generic.Emph (italic)
    - number → Number
    - string → String
    - boolean → Keyword.Constant
    """
    
    name = 'Zolo'
    aliases = ['zolo']
    filenames = ['*.zolo']
    mimetypes = ['text/x-zolo']
    
    tokens = {
        'root': [
            # ═════════════════════════════════════════════════════════
            # COMMENTS
            # ═════════════════════════════════════════════════════════
            # zlsp: TokenType.COMMENT
            (r'#.*$', Comment.Single),
            
            # Empty lines
            (r'^\s*$', Whitespace),
            
            # ═════════════════════════════════════════════════════════
            # ROOT-LEVEL KEYS (zlsp: TokenType.ROOT_KEY)
            # ═════════════════════════════════════════════════════════
            # Pattern: ^[A-Z][a-zA-Z0-9_]*:
            # Examples: Page_Header:, Core_Concepts_Section:
            (r'^([A-Z][a-zA-Z0-9_]*)'      # Root key (capitalized)
             r'(\([^)]+\))?'              # Optional type hint
             r'(\*|!|\^|~)?'              # Optional modifiers
             r'(:)',                        # Colon
             bygroups(Name.Class, Generic.Emph, Operator, Punctuation)),
            
            # ═════════════════════════════════════════════════════════
            # SPECIAL KEYS (zlsp: TokenType.ZMETA_KEY, etc.)
            # ═════════════════════════════════════════════════════════
            # zMeta, zRBAC, ~zNavBar*
            (r'^(\s*)'                     # Indentation
             r'(~?z(?:Meta|RBAC)|~zNavBar[a-zA-Z0-9_]*)'  # Special keywords
             r'(\*)?'                      # Optional modifier
             r'(:)',                        # Colon
             bygroups(Whitespace, Keyword.Namespace, Operator, Punctuation)),
            
            # ═════════════════════════════════════════════════════════
            # DISPLAY EVENT KEYS (zlsp: TokenType.UI_ELEMENT_KEY)
            # ═════════════════════════════════════════════════════════
            # Pattern: z[A-Z][a-zA-Z0-9]*:
            # Examples: zH1:, zText:, zMD:, zTable:, zUL:
            (r'(\s*)'                      # Indentation
             r'(z[A-Z][a-zA-Z0-9]*)'       # Display event (z + uppercase)
             r'(\([^)]+\))?'              # Optional type hint
             r'(\*|!)?'                    # Optional modifiers
             r'(:)',                        # Colon
             bygroups(Whitespace, Name.Function, Generic.Emph, Operator, Punctuation)),
            
            # ═════════════════════════════════════════════════════════
            # METADATA KEYS (zlsp: metadata attributes)
            # ═════════════════════════════════════════════════════════
            # Pattern: _z[A-Z][a-zA-Z]+: or _data: or _transaction:
            # Examples: _zClass:, _zStyle:, _zId:, _data:
            (r'(\s*)'                      # Indentation
             r'(_z[A-Z][a-zA-Z]+|_data|_transaction)'  # Metadata
             r'(:)',                        # Colon
             bygroups(Whitespace, Name.Variable, Punctuation)),
            
            # ═════════════════════════════════════════════════════════
            # PROPERTY KEYS (zlsp: TokenType.NESTED_KEY)
            # ═════════════════════════════════════════════════════════
            # Pattern: [a-z][a-zA-Z0-9_]*:
            # Examples: label:, content:, color:, href*:
            (r'(\s*)'                      # Indentation
             r'(\^|~)?'                    # Optional prefix modifier
             r'([a-z][a-zA-Z0-9_]*)'       # Property key (lowercase start)
             r'(\([^)]+\))?'              # Optional type hint
             r'(\*|!)?'                    # Optional suffix modifier
             r'(:)',                        # Colon
             bygroups(Whitespace, Operator, Name.Attribute, Generic.Emph, Operator, Punctuation)),
            
            # ═════════════════════════════════════════════════════════
            # VALUES (after colon)
            # ═════════════════════════════════════════════════════════
            include('values'),
        ],
        
        'values': [
            # ────────────────────────────────────────────────────────
            # ESCAPE SEQUENCES (zlsp: TokenType.ESCAPE_SEQUENCE)
            # ────────────────────────────────────────────────────────
            # Unicode escapes: \uXXXX, \UXXXXXXXX
            (r'\\[uU][0-9A-Fa-f]{4,8}', String.Escape),
            
            # Standard escapes: \n, \t, \r, etc.
            (r'\\[nrtbf\\"' + r"']", String.Escape),
            
            # ────────────────────────────────────────────────────────
            # BOOLEANS (zlsp: TokenType.BOOLEAN)
            # ────────────────────────────────────────────────────────
            (r'\b(true|false|True|False|yes|no|on|off)\b', Keyword.Constant),
            
            # ────────────────────────────────────────────────────────
            # NUMBERS (zlsp: TokenType.NUMBER)
            # ────────────────────────────────────────────────────────
            # Float with optional negative
            (r'-?\d+\.\d+', Number.Float),
            # Integer with optional negative
            (r'-?\d+', Number.Integer),
            
            # ────────────────────────────────────────────────────────
            # ARRAYS (zlsp: TokenType.BRACKET_STRUCTURAL)
            # ────────────────────────────────────────────────────────
            (r'\[', Punctuation, 'array'),
            (r'\]', Punctuation),
            
            # ────────────────────────────────────────────────────────
            # NULL VALUES (zlsp: TokenType.NULL)
            # ────────────────────────────────────────────────────────
            (r'\b(null|None)\b', Keyword.Constant),
            
            # ────────────────────────────────────────────────────────
            # STRINGS (zlsp: TokenType.STRING)
            # ────────────────────────────────────────────────────────
            # Everything else as value content (zolo's string-first philosophy)
            (r'[^\s\[\]#]+', String),
            
            # Whitespace
            (r'\s+', Whitespace),
        ],
        
        'array': [
            # Array content
            (r'\]', Punctuation, '#pop'),
            (r',', Punctuation),
            include('values'),
        ],
    }


def setup_lexer():
    """
    Register the lexer with Pygments so it can be used by language name.
    Called automatically when module is imported.
    """
    try:
        from pygments.lexers import get_lexer_by_name
        # Check if already registered
        try:
            get_lexer_by_name('zolo')
        except:
            # Not registered, do it now
            from pygments.lexers import LEXERS
            LEXERS['ZoloLexer'] = (
                'zOS.core.zSys.syntax.zolo_lexer',
                'Zolo',
                ('zolo',),
                ('*.zolo',),
                ('text/x-zolo',)
            )
    except ImportError:
        # Pygments not available, skip registration
        pass


# Auto-register when module is imported
setup_lexer()
