# zSys/zsyntax_bundle.py
"""
zsyntax_bundle — SSOT for the served Prism.js syntax bundle (.zolo highlighting).

The bundle (6 grammar JS files + 1 CSS theme) is generated by zolo-lsp at ITS
build time and shipped as package data — so the grammar the browser highlights
with always matches the parser the engine actually runs. zServer mounts the
directory read-only at a VERSIONED route:

    /zsyntax/<zolo-lsp version>/prism-zui.js  …

The version in the path is the cache strategy: the URL changes iff the
installed zolo-lsp changes, so a stale grammar after an upgrade is
structurally impossible — no ETag/conditional-GET machinery needed.

Consumed by BOTH halves of the seam (this module keeps them agreeing):
  * MountManager.auto_mount_zsyntax  — registers the mount.
  * html_injectors._inject_zui_head  — announces `syntaxBase` in zui-config.
    The client treats the announced value as an OPAQUE base URL (contract:
    never hardcode "/zsyntax/").

Degrades to None-everything when the installed zolo-lsp predates 1.2.0
(no `bifrost_prism_dir` accessor) or its bundle is missing: no mount, no
config field, no crash — the client falls back to its own bundled syntax/.
"""

from pathlib import Path
from typing import Optional, Tuple

# Reserved URL prefix — custom config mounts must not claim anything under it.
ZSYNTAX_PREFIX = "/zsyntax/"

_resolved: Optional[Tuple[Optional[str], Optional[Path]]] = None


def _resolve() -> Tuple[Optional[str], Optional[Path]]:
    """(base_url, bundle_dir) or (None, None). Cached — the installed zolo-lsp
    cannot change mid-process, so one probe per boot is correct."""
    global _resolved  # pylint: disable=global-statement
    if _resolved is not None:
        return _resolved
    try:
        import zlsp  # pylint: disable=import-outside-toplevel
        accessor = getattr(zlsp, "bifrost_prism_dir", None)
        if accessor is None:  # zolo-lsp < 1.2.0 — pre-bundle era
            _resolved = (None, None)
            return _resolved
        bundle = accessor()  # raises FileNotFoundError on a damaged install
        version = getattr(zlsp, "__version__", None) or "0"
        _resolved = (f"{ZSYNTAX_PREFIX}{version}/", Path(bundle))
    except Exception:  # pylint: disable=broad-except — any failure means "don't serve", never "crash boot"
        _resolved = (None, None)
    return _resolved


def zsyntax_base() -> Optional[str]:
    """Versioned URL base ("/zsyntax/1.2.0/") or None when unavailable."""
    return _resolve()[0]


def zsyntax_dir() -> Optional[Path]:
    """Filesystem dir of the installed bundle, or None when unavailable."""
    return _resolve()[1]
